config/routes.rb
Rails.application.routes.draw do

  resources :blogposts
  #get 'home/index'
  root 'home#index'

  get 'home/about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  before_action :set_blogpost, only: %i[ show edit update destroy ]

  # GET /blogposts or /blogposts.json
  def index
    @blogposts = Blogpost.all
  end

  # GET /blogposts/1 or /blogposts/1.json
  def show
  end

  # GET /blogposts/new
  def new
    @blogpost = Blogpost.new
  end

  # GET /blogposts/1/edit
  def edit
  end

  # POST /blogposts or /blogposts.json
  def create
    @blogpost = Blogpost.new(blogpost_params)

    respond_to do |format|
      if @blogpost.save
        format.html { redirect_to @blogpost, notice: "Blogpost was successfully created." }
        format.json { render :show, status: :created, location: @blogpost }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogposts/1 or /blogposts/1.json
  def update
    respond_to do |format|
      if @blogpost.update(blogpost_params)
        format.html { redirect_to @blogpost, notice: "Blogpost was successfully updated." }
        format.json { render :show, status: :ok, location: @blogpost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogposts/1 or /blogposts/1.json
  def destroy
    @blogpost.destroy
    respond_to do |format|
      format.html { redirect_to blogposts_url, notice: "Blogpost was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogpost
      @blogpost = Blogpost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blogpost_params
      params.require(:blogpost).permit(:first_name, :last_name, :title, :content, :url)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blogposts/_form.html.erb
<%= form_with(model: blogpost) do |form| %>
  <% if blogpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blogpost.errors.count, "error") %> prohibited this blogpost from being saved:</h2>

      <ul>
        <% blogpost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogposts/edit.html.erb
<h1>Editing Blogpost</h1>

<%= render 'form', blogpost: @blogpost %>

<%= link_to 'Show', @blogpost %> |
<%= link_to 'Back', blogposts_path %>

app/views/blogposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogposts</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Title</th>
      <th>Content</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogposts.each do |blogpost| %>
      <tr>
        <td><%= blogpost.first_name %></td>
        <td><%= blogpost.last_name %></td>
        <td><%= blogpost.title %></td>
        <td><%= blogpost.content %></td>
        <td><%= blogpost.url %></td>
        <td><%= link_to 'Show', blogpost %></td>
        <td><%= link_to 'Edit', edit_blogpost_path(blogpost) %></td>
        <td><%= link_to 'Destroy', blogpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blogpost', new_blogpost_path %>

app/views/blogposts/new.html.erb
<h1>New Blogpost</h1>

<%= render 'form', blogpost: @blogpost %>

<%= link_to 'Back', blogposts_path %>

app/views/blogposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @blogpost.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @blogpost.last_name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @blogpost.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blogpost.content %>
</p>

<p>
  <strong>Url:</strong>
  <%= @blogpost.url %>
</p>

<%= link_to 'Edit', edit_blogpost_path(@blogpost) %> |
<%= link_to 'Back', blogposts_path %>

app/views/home/_footer.html.erb
<footer class="footer">
    <div class="container">
        <span class="text-muted">Footer</span>
    </div>
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">CMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'Home', root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to 'About Us', home_about_path, class:"nav-link" %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<h2>Hello world</h2>
<p>homepage</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Title -->
    <title>CMS App</title>
    
  </head>
  <body>

    <%= render "home/header" %>
    
    <div class="container">
      <br />
      <%= yield %>
    </div>

    <%= render "home/footer" %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>